# Generated by Django 2.2 on 2021-01-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_many_to_many'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='pokemons', to='pokedex.Trainer'),
        ),
    ]
